# Generated by Django 3.2.7 on 2022-08-20 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_player_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='rank',
        ),
    ]
