# Generated by Django 3.2.7 on 2023-06-13 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_player_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='player',
            name='school',
        ),
        migrations.DeleteModel(
            name='School',
        ),
    ]
